M48
; DRILL file {KiCad (6.0.5)} date Fri May 20 09:36:30 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-20T09:36:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X2.1261Y-2.5758
X2.1261Y-2.6466
T2
X1.8151Y-5.4644
X1.8151Y-5.6553
T3
X1.6958Y-5.4526
X1.6958Y-5.6671
T0
M30
